### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by JoaoMarcosCSilva** [iacchus/birdears#25]
How can I build this from Windows 10?
I've downloaded it with `pip install birdears`, and I've downloaded, installed and added the installation folder to PATH from [https://sourceforge.net/projects/sox/files/sox/](https://sourceforge.net/projects/sox/files/sox/).
Still, when I type `birdears harmonic`, for instance, I get the following output:
```

                                       KEY: C major
                                       (chromatic: False; descending: False)

                                       Intervals P1  M2  M3  P4  P5  M6  M7  P8
                                       Scale     C4  D4  E4  F4  G4  A4  B4  C5
                                       Keyboard  z   x   c   v   b   n   m   ,

                                       ──────────────────────────────────────────
Exception in thread Thread-2:
Traceback (most recent call last):
  File "c:\users\paulo roberto\appdata\local\programs\python\python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\users\paulo roberto\appdata\local\programs\python\python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\paulo roberto\appdata\local\programs\python\python36\lib\site-packages\birdears\logger.py", line 111, in decorator
    return f(*args, **kwargs)
  File "c:\users\paulo roberto\appdata\local\programs\python\python36\lib\site-packages\birdears\sequence.py", line 86, in async_play
    self._play_chord(element, last_element=is_last)
  File "c:\users\paulo roberto\appdata\local\programs\python\python36\lib\site-packages\birdears\logger.py", line 111, in decorator
    return f(*args, **kwargs)
  File "c:\users\paulo roberto\appdata\local\programs\python\python36\lib\site-packages\birdears\sequence.py", line 167, in _play_chord
    subprocess.Popen(command.split())
  File "c:\users\paulo roberto\appdata\local\programs\python\python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "c:\users\paulo roberto\appdata\local\programs\python\python36\lib\subprocess.py", line 992, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado

```

**Comment by iacchus** [comment]
Can you please give the command `play.exe` in the command line and see if the system finds it?

**Comment by JoaoMarcosCSilva** [comment]
It didn't work, there's no such file in the system.
I also tried to install sox with pip instead, but it didn't help.

**Comment by JoaoMarcosCSilva** [comment]
Thanks for the quick answer!
After some quick research, I found [this](http://sox.10957.n7.nabble.com/sox-on-windows-play-exe-td3952.html), which states that the play and the sox command are interchangeable. Then I tried to rename my sox.exe file to play.exe and see what happens.
Now it worked, but sox couldn't recognize my speakers. I searched a little and found out that it was a problem with the current version, so I downloaded version 14.4.1 instead. Now it works perfectly.
You should check if the sox command works instead of play on linux. If it does, you can just set the program to use sox every time it uses play.
However, I am getting a new error now. It's unrelated, so I'll open a new issue.

**Comment by iacchus** [comment]
Ok, the analog command using `sox` or `sox.exe` is:

`sox.exe -n -d synth sin A4`

**Comment by iacchus** [comment]
It was patched and pushed to mainline.
